/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.agrologic.app.gui.rxtx.flock;

import com.agrologic.app.model.DataFormat;
import com.agrologic.app.model.Medicine;
import java.awt.Frame;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;

import javax.swing.JDialog;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class AddMedicineDialog extends JDialog {

    private Medicine currMedicine;
    private Long flockId;
    private FlockManagerService flockService;

    /**
     * Creates new form AddMedicineDialog
     */
    public AddMedicineDialog(Frame parent, boolean modal) {
        this(Long.valueOf(1), parent, modal);
    }

    public AddMedicineDialog(Long flockId, Frame owner, boolean modal) {
        super(owner, modal);
        initComponents();
        flockService = new FlockManagerService();
        this.flockId = flockId;
        loadMedicine(this.flockId);
        tblDataTable.addMouseListener(new MouseAdapter() {

            @Override
            public void mousePressed(MouseEvent e) {
                if (e.getButton() == MouseEvent.BUTTON1) {
                    // get the coordinates of the mouse click
                    Point p = e.getPoint();
                    // get the row index that contains that coordinate
                    int rowNumber = tblDataTable.rowAtPoint(p);
                    // get the ListSelectionModel of the JTable
                    ListSelectionModel model = tblDataTable.getSelectionModel();
                    // set the selected interval of rows. Using the "rowNumber"
                    // variable for the beginning and end selects only that one row.
                    model.setSelectionInterval(rowNumber, rowNumber);
                    Long id = (Long) tblDataTable.getModel().getValueAt(rowNumber, 0);
                    currMedicine = flockService.getMedicineById(id);
                    setForm(currMedicine);
                    btnAdd.setEnabled(false);
                    btnRemove.setEnabled(true);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDataTable = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnRemove = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add  Medicine");
        setMinimumSize(new java.awt.Dimension(570, 350));
        setModal(true);
        getContentPane().setLayout(null);

        tblDataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Amount", "Name", "Price", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDataTable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 11, 540, 170);

        btnAdd.setText("Add ");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd);
        btnAdd.setBounds(435, 195, 105, 23);

        jLabel2.setText("Amount");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 198, 140, 20);

        jLabel4.setText("Price");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 252, 140, 20);

        jLabel5.setText("Name");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 225, 140, 20);

        txtAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAmountKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAmountKeyTyped(evt);
            }
        });
        getContentPane().add(txtAmount);
        txtAmount.setBounds(170, 198, 226, 20);

        txtPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPriceKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPriceKeyTyped(evt);
            }
        });
        getContentPane().add(txtPrice);
        txtPrice.setBounds(170, 252, 226, 20);
        getContentPane().add(txtName);
        txtName.setBounds(170, 225, 226, 20);

        jLabel6.setText("Total");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 280, 140, 20);

        txtTotal.setEditable(false);
        txtTotal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                calcTotal(evt);
            }
        });
        getContentPane().add(txtTotal);
        txtTotal.setBounds(170, 280, 226, 20);

        btnRemove.setText("Delete");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemove);
        btnRemove.setBounds(435, 220, 105, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if (!validateForm()) {
            return;
        }

        Medicine medicine = getFromFields();
        flockService.addMedicine(medicine);
        loadMedicine(flockId);
        clearForm();

    }//GEN-LAST:event_btnAddActionPerformed

    private void calcTotal() {
        String samount = txtAmount.getText();
        String sprice = txtPrice.getText();
        int amount = Integer.parseInt(samount);
        float price = Float.parseFloat(sprice);
        float total = (float) (amount * price);
        txtTotal.setText("" + total);
    }

    private void calcTotal(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_calcTotal
        String samount = txtAmount.getText();
        String sprice = txtPrice.getText();
        int amount = Integer.parseInt(samount);
        float price = Float.parseFloat(sprice);
        float total = (float) (amount * price);
        txtTotal.setText("" + total);
    }//GEN-LAST:event_calcTotal

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        if(currMedicine == null) {
            return;
        }
        flockService.removeMedicine(currMedicine.getId());
        loadMedicine(flockId);
        clearForm();
        btnAdd.setEnabled(true);
        btnRemove.setEnabled(false);
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void txtAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAmountKeyTyped
        FlockGUIUtil.keyTypedHandler(txtAmount, evt);
    }//GEN-LAST:event_txtAmountKeyTyped

    private void txtAmountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAmountKeyReleased
        FlockGUIUtil.keyPressedHandler(txtAmount, evt);
        calcTotal();
    }//GEN-LAST:event_txtAmountKeyReleased

    private void txtPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriceKeyTyped
        FlockGUIUtil.keyTypedHandler(txtPrice, evt);
    }//GEN-LAST:event_txtPriceKeyTyped

    private void txtPriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriceKeyReleased
        FlockGUIUtil.keyPressedHandler(txtPrice, evt, DataFormat.DEC_2);
        calcTotal();
    }//GEN-LAST:event_txtPriceKeyReleased

    private void loadMedicine(Long flockId) {
        ((DefaultTableModel) tblDataTable.getModel()).getDataVector().removeAllElements();
        ((ListSelectionModel) tblDataTable.getSelectionModel()).setSelectionInterval(-1, -1);
        tblDataTable.revalidate();
        List<Medicine> medicineList = flockService.getAllMedicine(flockId);
        for (Medicine m : medicineList) {
            ((DefaultTableModel) tblDataTable.getModel()).insertRow(0, new Object[]{
                        m.getId(),
                        m.getAmount(),
                        m.getName(),
                        m.getPrice(),
                        m.getTotal()});
        }
    }

    private Medicine getFromFields() {
        Long flockId = Long.valueOf(1);
        String amount = txtAmount.getText();
        String name = txtName.getText();
        String price = txtPrice.getText();
        String total = txtTotal.getText();

        currMedicine = new Medicine();
        currMedicine.setAmount(Integer.parseInt(amount));
        currMedicine.setName(name);
        currMedicine.setFlockId(flockId);
        currMedicine.setPrice(Float.parseFloat(price));
        currMedicine.setTotal(Float.parseFloat(total));
        return currMedicine;
    }

    private boolean validateForm() {
        if (txtAmount.getText().equals("")
                || txtPrice.getText().equals("")
                || txtName.getText().equals("")
                || txtTotal.getText().equals("")) {
            return false;
        }
        return true;
    }

    private void clearForm() {
        txtAmount.setText("");
        txtPrice.setText("");
        txtName.setText("");
        txtTotal.setText("");
    }

    private void setForm(Medicine medicine) {
        txtAmount.setText("" + medicine.getAmount());
        txtPrice.setText("" + medicine.getPrice());
        txtName.setText("" + medicine.getName());
        txtTotal.setText("" + medicine.getTotal());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMedicineDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMedicineDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMedicineDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMedicineDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                AddMedicineDialog dialog = new AddMedicineDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnRemove;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDataTable;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
