/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.agrologic.app.gui.wizard;

import com.agrologic.app.config.Configuration;

/**
 *
 * @author Administrator
 */
public class ChooseLangauge extends javax.swing.JDialog {
    private Configuration configuration;
    /**
     * Creates new form ChooseLangauge
     */
    public ChooseLangauge(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.configuration = new Configuration();
        String lang = configuration.getLanguage();
        cmbLanguage.setSelectedItem(lang);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlServerStartup = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbLanguage = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlServerStartup.setBorder(javax.swing.BorderFactory.createTitledBorder("Language"));
        pnlServerStartup.setLayout(null);

        jLabel1.setText("Choose Language");
        pnlServerStartup.add(jLabel1);
        jLabel1.setBounds(30, 30, 100, 20);

        cmbLanguage.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "English", "Hebrew", "Chinese", "Russian", "French", "German" }));
        cmbLanguage.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbLanguageItemStateChanged(evt);
            }
        });
        pnlServerStartup.add(cmbLanguage);
        cmbLanguage.setBounds(140, 30, 100, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlServerStartup, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlServerStartup, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbLanguageItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbLanguageItemStateChanged
        String lang = (String) evt.getItem();
        configuration.setLanguage(lang);
        configuration.saveUpdatePreferences();
    }//GEN-LAST:event_cmbLanguageItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChooseLangauge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChooseLangauge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChooseLangauge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChooseLangauge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                ChooseLangauge dialog = new ChooseLangauge(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbLanguage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlServerStartup;
    // End of variables declaration//GEN-END:variables
}
